version: "3.8"
services:
  anythink-backend-python:
    build: ./backend
    container_name: anythink-backend-python
    command: >
      sh -c "cd backend &&
            poetry install &&
            poetry export -f "requirements.txt" --without-hashes --with-credentials > "requirements.txt"
            /wait-for-it.sh postgres-python:5432 -q -t 60 && 
            poetry run alembic upgrade head &&
            poetry run gunicorn app.main:app --worker-class=uvicorn.workers.UvicornWorker --bind=0.0.0.0:3000 --workers=5"
    working_dir: /usr/src
    volumes:
      - ./:/usr/src
    ports:
      - "3000:3000"
    environment:
      - APP_ENV=dev
      - SECRET_KEY=secret
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:@postgres-python:5432/anythink-market
      - GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN=${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
    depends_on:
      - "postgres-python"

  anythink-frontend-react:
    build: ./frontend
    container_name: anythink-frontend-react
    command: sh -c "cd frontend && yarn install && /wait-for-it.sh anythink-backend-python:3000 -t 120 --strict -- curl --head -X GET --retry 30 --retry-connrefused --retry-delay 1 anythink-backend-python:3000/api/ping && yarn start"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REACT_APP_BACKEND_URL=${CODESPACE_BACKEND_URL:-http://localhost:3000}
      - WDS_SOCKET_PORT=${CODESPACE_WDS_SOCKET_PORT:-3001}
    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
      - /usr/src/frontend/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - "anythink-backend-python"

  postgres-python:
    container_name: postgres-python
    restart: on-failure
    image: postgres
    logging:
      driver: none
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: anythink-market
    volumes:
      - ~/postgres/data:/data/db
    ports:
      - '5433:5432'

  anythink-ack:
    build: ./frontend
    container_name: anythink-ack
    command: sh -c "/wait-for-it.sh anythink-frontend-react:3001 -q -t 1000 && ./anythink_ack.sh"
    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
    depends_on:
      - "anythink-frontend-react"
